"""empty message

Revision ID: 001d8801cabb
Revises: 0166397f12d2
Create Date: 2022-11-22 20:19:53.177814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001d8801cabb'
down_revision = '0166397f12d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###